"""asyncssh transport: one connection per call, key auth only, strict host key.

The private key is generated by the config flow (`generate_keypair`) and
lives in the config entry. The server host key is stored on first contact
(`fetch_host_key`) and enforced afterwards — a changed key raises
`SSHHostKeyError` instead of being accepted silently.
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass

import asyncssh

from .const import CONNECT_TIMEOUT, KEY_COMMENT


class SSHError(Exception):
    """Base class."""


class SSHConnectError(SSHError):
    """Host unreachable, port closed, DNS failure."""


class SSHAuthError(SSHError):
    """The server rejected the key."""


class SSHHostKeyError(SSHError):
    """The server presented a host key that differs from the stored one."""


class SSHTimeout(SSHError):
    """Connect or command exceeded its timeout."""


class SSHKeyError(SSHError):
    """A stored or given key could not be parsed."""


@dataclass
class CommandResult:
    exit_status: int
    stdout: str
    stderr: str


def generate_keypair() -> tuple[str, str]:
    """Return (private key in OpenSSH format, public key line with our comment)."""
    key = asyncssh.generate_private_key("ssh-ed25519", comment=KEY_COMMENT)
    private = key.export_private_key("openssh").decode()
    public = key.export_public_key("openssh").decode().strip()
    return private, public


def fingerprint(public_key_line: str) -> str:
    try:
        return asyncssh.import_public_key(public_key_line).get_fingerprint()
    except asyncssh.KeyImportError as err:
        raise SSHKeyError(f"public key unreadable: {err}") from err


async def fetch_host_key(host: str, port: int) -> str:
    """Trust on first use: read the server's host key without authenticating."""
    try:
        key = await asyncio.wait_for(asyncssh.get_server_host_key(host, port=port), CONNECT_TIMEOUT)
    except asyncio.TimeoutError as err:
        raise SSHTimeout(f"timeout reading host key of {host}:{port}") from err
    except (OSError, asyncssh.Error) as err:
        raise SSHConnectError(str(err)) from err
    if key is None:
        raise SSHConnectError("server sent no host key")
    return key.export_public_key("openssh").decode().strip()


class UnraidSSH:
    """Run one command over a fresh connection."""

    def __init__(self, host: str, port: int, private_key: str, host_key: str) -> None:
        self._host = host
        self._port = port
        try:
            self._client_key = asyncssh.import_private_key(private_key)
        except asyncssh.KeyImportError as err:
            raise SSHKeyError(f"private key unreadable: {err}") from err
        self._host_key = host_key

    async def _connect(self) -> asyncssh.SSHClientConnection:
        # An unreadable stored host key is only a host key problem once we
        # actually reach a server; an empty trusted list makes asyncssh reject
        # whatever the server offers. A closed port still fails as a connect
        # error, which is what the caller needs to see.
        try:
            trusted = [asyncssh.import_public_key(self._host_key)]
            unreadable = ""
        except asyncssh.KeyImportError as err:
            trusted = []
            unreadable = f"stored host key unreadable: {err}"
        try:
            return await asyncio.wait_for(
                asyncssh.connect(
                    self._host,
                    port=self._port,
                    username="root",
                    client_keys=[self._client_key],
                    known_hosts=(trusted, [], []),
                    connect_timeout=CONNECT_TIMEOUT,
                ),
                CONNECT_TIMEOUT + 2,
            )
        except asyncio.TimeoutError as err:
            raise SSHTimeout(f"connect to {self._host}:{self._port} timed out") from err
        except asyncssh.HostKeyNotVerifiable as err:
            raise SSHHostKeyError(unreadable or str(err)) from err
        except asyncssh.PermissionDenied as err:
            raise SSHAuthError(str(err)) from err
        except (OSError, asyncssh.Error) as err:
            raise SSHConnectError(str(err)) from err

    async def run(self, command: str, timeout: float) -> CommandResult:
        conn = await self._connect()
        try:
            result = await asyncio.wait_for(conn.run(command, check=False), timeout)
        except asyncio.TimeoutError as err:
            raise SSHTimeout(f"command timed out after {timeout}s") from err
        except (OSError, asyncssh.Error) as err:
            raise SSHConnectError(str(err)) from err
        finally:
            # close() only asks; wait_closed() lets the connection's own tasks
            # finish. Without it every poll leaves a pending task behind --
            # "Task was destroyed but it is pending!" in the log, at the poll
            # interval, forever.
            conn.close()
            await conn.wait_closed()
        return CommandResult(
            exit_status=result.exit_status if result.exit_status is not None else -1,
            stdout=result.stdout if isinstance(result.stdout, str) else result.stdout.decode(),
            stderr=result.stderr if isinstance(result.stderr, str) else result.stderr.decode(),
        )
